### ISSUE TITLE
Add others to Hasura project

### ISSUE THREAD

**Issue by kmchmk** [kmchmk/SimplestGameEver#11]
Add others (Chanaka, Dulaj and Mahel) to the new Hasura project (#2) as ADMINS. Give us all the permissions possible.

My email is kmchmk@gmail.com
@dulaj93 What is your email? (You have to sign up to [hasura.io](http://hasura.io/) to create your account. #8 )

**Comment by dulaj93** [comment]
My email, dulaj.sac@gmail.com
