### ISSUE TITLE
Share the Hasura console URL and password

### ISSUE THREAD

**Issue by kmchmk** [kmchmk/SimplestGameEver#12]
As I mentioned in #2 you have to share the password with others in our group chat. Do not commit the password into git.
Also you have to share the console URL with others. That link, you can add here as a comment.

Explanation:
From #2 you created a Hasura project. Now others will be using it. So you have to share the console URL and password with others. Also in #11 you have to give others full admin permission to Hasura project.

Please follow this guide. : https://hasura.io/docs/latest/graphql/cloud/getting-started/index/

In the first screenshot of the above guide, when you click the "Launch Console" button, it will open the Hasura console. You have to share that Hasura console URL with us.

**Comment by dusqut** [comment]
How to change hasura project password ?

**Comment by kmchmk** [comment]
Why is this ticket still open? Please close when you are done.

**Comment by kmchmk** [comment]
What are you talking about? Please read carefully.
