### ISSUE TITLE
Create A Hasura Project

### ISSUE THREAD

**Issue by kmchmk** [kmchmk/SimplestGameEver#2]
- We will be using a [Hasura ](https://hasura.io/) GraphQL backend.
- Create a free tier Hasura project with Heroku PostgreSQL database.
- **_Do not commit the password into git. Share it in our group chat._**

**Comment by dusqut** [comment]
https://cloud.hasura.io/project/00d2b353-ae80-4248-ba8a-1abaef0be8fe/console/api/api-explorer

**Comment by kmchmk** [comment]
> https://cloud.hasura.io/project/00d2b353-ae80-4248-ba8a-1abaef0be8fe/console/api/api-explorer

We can't access this link. Check #11
